export const constants = {
  "RANDOMIZATION_INTERVAL": 2000,
  "VARIABLE_INTERVAL": 1000,
  "MIN_BUTTONS": 3,
  "MAX_BUTTONS": 7,
  "DEFAULT_BUTTON_HEIGHT": "5em",
  "DEFAULT_BUTTON_WIDTH": "10em",
  "BUTTON_Y_POSITION": "15em",
  "BUTTON_X_SPACING": 10.2
} 